### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by EiraStudios**
I've fixed a typo in the `README.md`. Updated the plugin version number in the metadata, so that when it's pushed to the WordPress plugin directory, it'll register as a new update, and optimised `fold_spacetime()` with the removal of some redundant logic.

### CODE REVIEW

**Comment by jhabdas** [comment]
Please see [Contributing](https://github.com/comfusion/hyperdrive#contributing) section of the `README.md` for a refresher on the plugin contributing guidelines, specifically the part which states:

> Please open issues when creating PRs and PR against the issue to close it. This helps separate the need (the issue) from the implementation (the pull), resulting in more robust solutions.

Without a clear _need_ pull requests lose value and may otherwise impede ongoing prioritized development activities. I let it slide for #25 to help encourage first-time contributions. And while I welcome some of the refactoring in here (I was never pleased with my weirdo _make it work_ logic which appears to be pithily being refactored) I am becoming aware of the possibility some small differences in PHP may be causing the unnecessary introduction of code into this repo and will no longer review pulls changing the codebase until #9 and #4 (at least unit tests) is complete.

**Comment by EiraStudios** [comment]
Sorry about that, with the changes only being very minor I didn't think they'd need an issue creating, but noted for the future.

> I am becoming aware of the possibility some small differences in PHP may be causing the unnecessary introduction of code into this repo

Which code? The code I've submitted? The only change I can think of that was added for a specific PHP version was the _pass-by-reference_ error in PHP7; which as more servers move to PHP7 as the default version (hopefully sooner rather than later) it's important to ensure forward compatibility.

Feel free to close this pull request then, it will probably be pretty outdated before PRs are accepted again, and you've already committed at least one of the changes here now yourself.

**Comment by jhabdas** [comment]
We can leave it open. It has some good refactoring I'd like to incorporate. Just need to ensure we're backed by unit tests before we start changing anything else. We've got a small enough codebase 100% test coverage should be achievable and I'll set-up CI to fail the build if coverage levels fall before a reasonable threshold (if it makes sense right now).

As for what's causing what, I'm not sure. The tests will help us understand that. If you have time, please consider looking at the following as it was the initial prototype for this plugin and includes some of the code we'll need to hit 1.0.0 after the test framework and CI is in place: https://gist.github.com/jhabdas/64e8380010e43a526fb9c9ee511fad17

**Comment by jhabdas** [comment]
@EiraStudios #4 is unblocked by #9 and #32. If you'd like to help start writing unit tests I'd like to see a PR for an example unit test which follows best practices and ideally doesn't use classes so we may use it as a model for more tests and unblock this pull request.

**Comment by jhabdas** [comment]
Also, sorry for merging into your branch. That's not something I usually do but couldn't resist trying the merge button on GH. Please feel free to rebase out that commit and force push over it to rewrite history.

**Comment by jhabdas** [comment]
Following up here. [Contributing guidelines](https://github.com/comfusion/hyperdrive#contributing) have been updated based on learnings from this issue and are now available in 3 languages.

**Comment by jhabdas** [comment]
Changeset no longer applicable with https://github.com/comfusion/hyperdrive/blob/master/CHANGELOG.md#100-beta5-2017-05-31

**Pull request closed without merging**
